spring.application.name=acs_lab2
spring.datasource.url=jdbc:postgresql://localhost:5432/acs_library
spring.datasource.username=postgres
spring.datasource.password=06042003
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mvc.hiddenmethod.filter.enabled=true

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=true

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=acs.lab.library@gmail.com
spring.mail.password=wgri rxkq jctd tctc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

topic.name=entity.change.queue