spring.application.name=acs_lab2
spring.datasource.url=jdbc:postgresql://localhost:5432/acs_library
spring.datasource.username=postgres
spring.datasource.password=06042003
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.mvc.hiddenmethod.filter.enabled=true
